/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

/* Table schema:
CREATE TABLE kv_store_623b2a1c (
  key TEXT NOT NULL PRIMARY KEY,
  value JSONB NOT NULL
);
*/

// View at https://supabase.com/dashboard/project/hdzqdlxorkghslaijjzo/database/tables

// This file provides a simple key-value interface for storing Figma Make data. It should be adequate for most small-scale use cases.
import { createClient } from "jsr:@supabase/supabase-js@2.49.8";

// Singleton client — created once per Edge Function instance, reused for all calls.
const _client = createClient(
  Deno.env.get("SUPABASE_URL"),
  Deno.env.get("SUPABASE_SERVICE_ROLE_KEY"),
);

// Set stores a key-value pair in the database.
export const set = async (key: string, value: any): Promise<void> => {
  const { error } = await _client.from("kv_store_623b2a1c").upsert({ key, value });
  if (error) throw new Error(error.message);
};

// Get retrieves a key-value pair from the database.
export const get = async (key: string): Promise<any> => {
  const { data, error } = await _client.from("kv_store_623b2a1c").select("value").eq("key", key).maybeSingle();
  if (error) throw new Error(error.message);
  return data?.value;
};

// Delete deletes a key-value pair from the database.
export const del = async (key: string): Promise<void> => {
  const { error } = await _client.from("kv_store_623b2a1c").delete().eq("key", key);
  if (error) throw new Error(error.message);
};

// Sets multiple key-value pairs in the database.
export const mset = async (keys: string[], values: any[]): Promise<void> => {
  const { error } = await _client.from("kv_store_623b2a1c").upsert(keys.map((k, i) => ({ key: k, value: values[i] })));
  if (error) throw new Error(error.message);
};

// Gets multiple key-value pairs from the database, preserving input key order.
export const mget = async (keys: string[]): Promise<any[]> => {
  if (keys.length === 0) return [];
  const { data, error } = await _client.from("kv_store_623b2a1c").select("key, value").in("key", keys);
  if (error) throw new Error(error.message);
  // SQL IN() may return rows in any order — re-sort to match input key order.
  const map = new Map((data ?? []).map((d) => [d.key, d.value]));
  return keys.map((k) => map.get(k) ?? null);
};

// Deletes multiple key-value pairs from the database.
export const mdel = async (keys: string[]): Promise<void> => {
  if (keys.length === 0) return;
  const { error } = await _client.from("kv_store_623b2a1c").delete().in("key", keys);
  if (error) throw new Error(error.message);
};

// Search for key-value pairs by prefix — fetches ALL rows in 1000-row chunks.
export const getByPrefix = async (prefix: string): Promise<any[]> => {
  const all: any[] = [];
  const chunkSize = 1000;
  let offset = 0;
  while (true) {
    const { data, error } = await _client
      .from("kv_store_623b2a1c")
      .select("key, value")
      .like("key", prefix + "%")
      .range(offset, offset + chunkSize - 1);
    if (error) throw new Error(error.message);
    if (!data || data.length === 0) break;
    all.push(...data.map((d) => d.value));
    if (data.length < chunkSize) break;
    offset += chunkSize;
  }
  return all;
};

// Count rows matching a prefix without fetching data.
export const countByPrefix = async (prefix: string): Promise<number> => {
  const { count, error } = await _client
    .from("kv_store_623b2a1c")
    .select("*", { count: "exact", head: true })
    .like("key", prefix + "%");
  if (error) throw new Error(error.message);
  return count ?? 0;
};

// Paginated prefix search filtered to entries missing name (note) or address.
export const getFlaggedPaged = async (
  prefix: string,
  offset: number,
  limit: number,
  orderBy: string[] = [],
): Promise<{ data: any[]; total: number }> => {
  let query = (_client as any)
    .from("kv_store_623b2a1c")
    .select("key, value", { count: "exact" })
    .like("key", prefix + "%")
    .or("value->>note.is.null,value->>note.eq.,value->>address.is.null,value->>address.eq.,value->>city.is.null,value->>city.eq.,value->>state.is.null,value->>state.eq.,value->>zip.is.null,value->>zip.eq.");

  for (const field of orderBy) {
    query = query.order(`value->>${field}`, { ascending: true, nullsFirst: false });
  }

  const { data, count, error } = await query.range(offset, offset + limit - 1);
  if (error) throw new Error(error.message);
  return { data: (data ?? []).map((d: any) => d.value), total: count ?? 0 };
};

// Paginated prefix search with optional filters and full-text search.
// filters: { flagged?, state?, source?, search? }
export const getByPrefixFiltered = async (
  prefix: string,
  offset: number,
  limit: number,
  orderBy: string[] = [],
  filters: { flagged?: boolean; state?: string; source?: string; search?: string } = {},
): Promise<{ data: any[]; total: number }> => {
  let query = (_client as any)
    .from("kv_store_623b2a1c")
    .select("key, value", { count: "exact" })
    .like("key", prefix + "%");

  if (filters.flagged) {
    query = query.or("value->>note.is.null,value->>note.eq.,value->>address.is.null,value->>address.eq.,value->>city.is.null,value->>city.eq.,value->>state.is.null,value->>state.eq.,value->>zip.is.null,value->>zip.eq.");
  }
  if (filters.state) {
    query = query.eq("value->>state", filters.state);
  }
  if (filters.source) {
    query = query.eq("value->>source", filters.source);
  }
  if (filters.search) {
    const s = filters.search.toLowerCase();
    // Search across note, address, city, state, zip using ilike
    query = query.or(
      `value->>note.ilike.%${s}%,value->>address.ilike.%${s}%,value->>city.ilike.%${s}%,value->>state.ilike.%${s}%,value->>zip.ilike.%${s}%`
    );
  }

  for (const field of orderBy) {
    query = query.order(`value->>${field}`, { ascending: true, nullsFirst: false });
  }

  const { data, count, error } = await query.range(offset, offset + limit - 1);
  if (error) throw new Error(error.message);
  return { data: (data ?? []).map((d: any) => d.value), total: count ?? 0 };
};

// Paginated prefix search — returns one page of results plus the total count.
// orderBy: array of JSONB field names inside `value` to sort by (ascending).
// e.g. ["state", "city", "zip"] → ORDER BY value->>'state', value->>'city', value->>'zip'
export const getByPrefixPaged = async (
  prefix: string,
  offset: number,
  limit: number,
  orderBy: string[] = [],
): Promise<{ data: any[]; total: number }> => {
  let query = _client
    .from("kv_store_623b2a1c")
    .select("key, value", { count: "exact" })
    .like("key", prefix + "%");

  for (const field of orderBy) {
    // PostgREST supports ordering by JSONB text fields via the ->>'field' syntax.
    query = (query as any).order(`value->>${field}`, { ascending: true, nullsFirst: false });
  }

  const { data, count, error } = await query.range(offset, offset + limit - 1);
  if (error) throw new Error(error.message);
  return { data: (data ?? []).map((d) => d.value), total: count ?? 0 };
};